---
author:
  email: 
  name: An Author
  twitter: 
  url: 
baseurl: "/original-sacred-harp-first-50"
collections:
  annotations:
    output: true
    permalink: "/annotations/:path/"
  volume_pages:
    output: true
    permalink: "/pages/:path/"
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    layout: volume_page
    short_label: p.
    deep_zoom: true
    extra_js:
    - volume-page.js
    - hammer.min.js
    - deepzoom.js
    - openseadragon.min.js
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
gems:
- jekyll-sitemap
homepage_image: https://readux.ecds.emory.edu/books/emory:r8qzb/pages/emory:r8r0k/single-page/
image_size:
  page:
    width: 1000
    height: 825
  thumbnail:
    width: 300
    height: 247
  small-thumbnail:
    width: 100
    height: 82
permalink: pretty
publication_info:
  title: 'Original sacred harp : containing a superior collection of standard melodies,
    of odes, anthems, and church music, and hymns of high repute : rudiments, retaining
    all valuable standard regulations, arr. with all modern up-to-date improvements.,
    an annotated digital edition'
  date: '2017'
  author: B F White; E J King; J S James.
  editors:
  - Jesse Pearlman Karlsberg
  - Robert Dunn
  tei_xml: tei.xml
show_annotation_author: true
source_info:
  title: 'Original sacred harp : containing a superior collection of standard melodies,
    of odes, anthems, and church music, and hymns of high repute : rudiments, retaining
    all valuable standard regulations, arr. with all modern up-to-date improvements.'
  author: B F White; E J King; J S James.
  date: '1911'
  url: https://readux.ecds.emory.edu/books/emory:r8qzb/
  pdf_url: https://readux.ecds.emory.edu/books/emory:r8qzb/pdf/
  via_readux: true
tagline: ", an annotated digital edition"
title: 'Original sacred harp : containing a superior collection of standard melodies,
  of odes, anthems, and church music, and hymns of high repute : rudiments, retaining
  all valuable standard regulations, arr. with all modern up-to-date improvements.'
url: https://Robdunn13.github.io
version: 0.7
